apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Release.Name }}-{{ .Chart.Name }}"
  labels:
    app.kubernetes.io/name: {{ include "vault.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  gateways:
  - global-gateway.istio-system.svc.cluster.local
  hosts:
  - "{{ .Release.Name }}.ecc-dev.progressoft.cloud"
  http:
    - match:
      - uri:
          prefix: "/"
      route:
      - destination:
          host: "{{ .Release.Name }}"
          port:
            number: 8200
      headers:
        request:
          add:
            x-forwarded-port: "443"